views.filter_value.translation_used_count:
  type: mapping
  label: 'Numeric'
  mapping:
    min:
      type: string
      label: 'Min'
    max:
      type: string
      label: 'And max'
    value:
      type: string
      label: 'Value'